service: tasks-backend-api
frameworkVersion: '2'
provider:
  name: aws
  runtime: java8
  #lambdaHashingVersion: 20201221
  region: eu-west-2
  profile: serverless
  environment:
    DB_HOST: ${file(./config.dev.json):DB_HOST}
    DB_NAME: ${file(./config.dev.json):DB_NAME}
    DB_USER: ${file(./config.dev.json):DB_USER}
    DB_PASSWORD: ${file(./config.dev.json):DB_PASSWORD}
package:
  artifact: target/tasks-api-java-dev.jar
functions:
  get-restaurant-api:
    handler: com.impact.GetRestaurantHandler
    events:
      - http:
          path: /restaurants
          method: get
  get-allergen-api:
    handler: com.impact.GetAllergenHandler
    events:
      - http:
          path: /allergens
          method: get
  get-menuitem-api:
    handler: com.impact.GetMenuItemHandler
    events:
      - http:
          path: /menuitems
          method: get
  get-menuitem-allergens-api:
    handler: com.impact.GetMenuItemsAllergenHandler
    events:
      - http:
          path: /menuallergens
          method: get
  
  
  


